version: '3.4'

services:
  helsi.web:
    image: ${DOCKER_REGISTRY-}helsiweb
    build:
      context: .
      dockerfile: Helsi.Web\Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - esdata:/usr/share/elasticsearch/data
    networks:
        - esnetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
        - "5601:5601"
    networks:
        - esnetwork
    depends_on:
        - elasticsearch
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: nat